ktor:
  application:
    modules:
      - org.delcom.ApplicationKt.module
  deployment:
    port: 8080
    host: 0.0.0.0

  database:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    name: ${DB_NAME:proyek1_library}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jwt:
    secret: ${JWT_SECRET:rahasia123}